[package]
name = "inbox3"
version = "1.0.0"
authors = []

[addresses]
inbox3_addr = "_"
std = "0x1"

[dev-addresses]
inbox3_addr = "0x123"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
